services:
  reserva_api:
    build:
      context: .
      dockerfile: Servicios/Reservas/Reserva.Api/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    init: true
    depends_on:
      - reserva_db
    networks:
      - reservanet
  reserva_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "-Vyte123456!"
      ACCEPT_EULA: "Y"
    networks:
      - reservanet
  
  kong-database:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong_data:/var/lib/postgresql/data
    networks:
      - reservanet

  kong:
    image: kong:latest
    depends_on:
      - kong-database
    networks:
      - reservanet
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "8000:8000" # Public access
      - "8001:8001" # Admin API
      - "8443:8443" # HTTPS public access
      
  konga:
    image: pantsel/konga
    ports:
      - "1337:1337"
    environment:
      DB_ADAPTER: postgres
      DB_HOST: konga_db
      DB_PORT: 5432
      DB_USER: kongauser
      DB_PASSWORD: kongapass
      DB_DATABASE: kongadb
    depends_on:
      - konga_db

  # Base de datos para Konga
  konga_db:
    image: postgres:10
    environment:
      POSTGRES_USER: kongauser
      POSTGRES_PASSWORD: kongapass
      POSTGRES_DB: kongadb
    volumes:
      - konga_data:/var/lib/postgresql/data  
volumes:
  db_data:
  kong_data:
  konga_data:

networks:
  reservanet:
    driver: bridge