// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Turnos.Infrastructure.Persistence;

#nullable disable

namespace Turnos.Infrastructure.Migrations
{
    [DbContext(typeof(TurnosDbContext))]
    [Migration("20250514183524_turnos3")]
    partial class turnos3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Turnos.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SlotId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("Turnos.Domain.Entities.Slot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("Turnos.Domain.Entities.Turno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Turnos", (string)null);
                });

            modelBuilder.Entity("Turnos.Domain.Entities.Slot", b =>
                {
                    b.OwnsOne("Turnos.Domain.ValueObjects.IntervaloTiempo", "Horario", b1 =>
                        {
                            b1.Property<Guid>("SlotId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("SlotId");

                            b1.ToTable("Slots");

                            b1.WithOwner()
                                .HasForeignKey("SlotId");
                        });

                    b.Navigation("Horario")
                        .IsRequired();
                });

            modelBuilder.Entity("Turnos.Domain.Entities.Turno", b =>
                {
                    b.OwnsOne("Turnos.Domain.ValueObjects.IntervaloTiempo", "Horario", b1 =>
                        {
                            b1.Property<Guid>("TurnoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Fin")
                                .HasColumnType("datetime2")
                                .HasColumnName("FechaHoraFin");

                            b1.Property<DateTime>("Inicio")
                                .HasColumnType("datetime2")
                                .HasColumnName("FechaHoraInicio");

                            b1.HasKey("TurnoId");

                            b1.HasIndex("Inicio")
                                .HasDatabaseName("IX_Turnos_FechaHoraInicio");

                            b1.ToTable("Turnos");

                            b1.WithOwner()
                                .HasForeignKey("TurnoId");
                        });

                    b.Navigation("Horario")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
